### ISSUE TITLE
04.25. Zeit- und Rolleneinteilung / Terminvorbereitung / Doku

### ISSUE THREAD

**Issue by chantoEW** [chantoEW/Students-Lab#4]
# Rolleneinteilung
Clown: @Joelk42 
Macher: @faschlag 
Zeitmanager: @maxwehning 
Koordinator: @chantoEW 
[Quelle](https://wpgs.de/fachtexte/teamrollen-nach-belbin/)

# To-Dos
- [x] @maxwehning: Gantt Diagramm 
- [x] @Joelk42: Mailverfassung Dirks (Ziel: Bestellliste und detaillierte Vorgehensweise)
- [ ] @faschlag: Überarbeitung der Dokumentation  
- [ ] @chantoEW: Überarbeitung der Issue-Struktur, Terminvorbereitung
- [x] @ alle: Terminabstimmung mit Dirks

**Comment by chantoEW** [comment]
Terminvorschläge:
02.04. oder 09.04.: 8:15 Uhr - 11:30 Uhr / ab 15:45 Uhr 
08.04.: ab 12:00 Uhr

**Comment by chantoEW** [comment]
# Terminvorbereitung
IDEE: 
Entwicklung eines smarten Getränkeuntersetzers mit LEDs. 
Der Untersetzer leuchte Rot, sobald anhand des Gewichtes des Behälters erkannt wurde, dass bis zu dem aktuellen Zeitpunkt zu wenig getrunken wurde.
Der Untersetzer soll mit einer App/Webanwendung verbunden werden, auf der die ausgewerteten Daten dargestellt werden (wie z.B. eine Smartwatch).

ZIEL: 
Durch wiederholte Erinnerung des Untersetzers, das Trinkverhalten am Arbeitsplatz optimieren (ca. 2-3 Liter/Tag).

NOTWENDIGE HARDWARE:
 - Waage
 - LED Ring
 - Platine (ätzen) mit ESP 32 [www.az-delivery.de](https://www.az-delivery.de/products/esp32-developmentboard)
 - Webserver

NOTWENDIGE SOFTWARE:
- ?
